### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TanguyOrtegat** [maxux/toogoodtogo-watcher#2]
Hello! 

Thanks for making that simple script. It works great but...
Pay attention, becasue there are some typo erros when running the bot.

Sometime it is stuck and got this error, any idea why ?
`Traceback (most recent call last):
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\utils\request.py", line 225, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 665, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tangu\Desktop\toogoodtogo-watcher-master\Python\toogoodtogo.py", line 394, in <module>
    tgtg = TooGoodToGo()
  File "C:\Users\tangu\Desktop\toogoodtogo-watcher-master\Python\toogoodtogo.py", line 356, in watch

  File "C:\Users\tangu\Desktop\toogoodtogo-watcher-master\Python\toogoodtogo.py", line 210, in available
    print("[+]   == NEW ITEMS AVAILABLE ==")
  File "C:\Users\tangu\Desktop\toogoodtogo-watcher-master\Python\toogoodtogo.py", line 337, in notifier

  File "<decorator-gen-2>", line 2, in send_message
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\bot.py", line 70, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\bot.py", line 349, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\bot.py", line 178, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\utils\request.py", line 331, in post
    result = self._request_wrapper('POST', url,
  File "C:\Users\tangu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telegram\utils\request.py", line 231, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`

After my question i got also a remark. I've seen into the code that you did write basket? Possible to further work on it ? Would be a great addon!

**Comment by maxux** [comment]
Thanks for your bug report.

It weird, latest code should handle network error. This could be related to your network connection. I have the script running for days now without any interruption. Try to auto-restart script if this happen rarely. Otherwise I'll improve error catching.

About basket, I had some preliminary code to handle auto-reservation/payment but I could not finish it, didn't had chance to test/capture traffic and current circumstance make me using too good to go less often than before :/

I hope maybe improve that later.

**Comment by TanguyOrtegat** [comment]
Thanks for your fast reply. I've put the script 9n home network when I had that issue,now I did put on dedicated server and we will see.
Yea till now didnt see any script handle auto buying

**Comment by TanguyOrtegat** [comment]
Now running on dedicated server, sometime i got this erro ...
![image](https://user-images.githubusercontent.com/17274032/81716007-2a4f1180-9479-11ea-87e1-9d60d90ac3cc.png)

![image](https://user-images.githubusercontent.com/17274032/81716045-34711000-9479-11ea-9edb-3794e6af2c64.png)

**Comment by TanguyOrtegat** [comment]
it was because bad internet connection
