### ISSUE TITLE
403 error when using api login

### ISSUE THREAD

**Issue by larkaa** [maxux/toogoodtogo-watcher#6]
Looks like the the api login is down or has changed -- might be connected to the version number in the user agent: https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/22

**Comment by andreaseide80** [comment]
If you post your error message, it will be easier to help you :)

**Comment by larkaa** [comment]
Oops. Here you go. I added a print of the response status code and the response text for information.

```
[+] authentication: login using <XXX> email

<Response [403]> 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: eDTV7zMF75w1y7MbjhIk5hfrUFMd1_jhRmj8vyfNe-WIPNBorGtQOw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
Traceback (most recent call last):
  File "toogoodtogo.py", line 401, in <module>
    tgtg.watch()
  File "toogoodtogo.py", line 351, in watch
    self.login()
  File "toogoodtogo.py", line 110, in login
    data = r.json()
  File "XXX/anaconda3/envs/ai/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "XXX/anaconda3/envs/ai/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "XXX/anaconda3/envs/ai/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "XXX/anaconda3/envs/ai/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by maxux** [comment]
I just updated code to use favourite `/v5/` endpoint, but didn't changed login process. It still works for me (I don't use same UserAgent than node version, I used a more recent one directly).

Are you sure your credentials are right ?

Pull master and start from scratch by removing `~/.config/tgtgw/config.json` file.

**Comment by larkaa** [comment]
My IP was blocked, which explains the error. I don't get it if I use the app on 4G, but I do get an error when using the app on my home wifi. Sending them an email about it - seems like it's not just me.

**Comment by larkaa** [comment]
The issue was solved by requesting an IP refresh from my ISP. With the update of the user agent and the change for api v5, everything works fine!
